# Generated by Django 5.0.3 on 2024-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('highest_qualification', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resume/')),
                ('cover_letter', models.FileField(upload_to='coverletter/')),
            ],
        ),
    ]
