file = open ('welcome.txt', 'w')
file.write('hi all myself aswinganesh\n' )
file.write('good\n')
file.write('morning\n')
file.write('how are you\n')
file.close()
file = open ('welcome.txt', 'r')
print(file.read())
file.close()